version: '3'

services:
#  backend:
#    build: .
#    ports:
#      - "8000:8000"
#    restart: always
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  app:
    build: .
    command: bash -c "uvicorn main:app --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

  redis:
    image: redis:6.2-alpine
    ports:
      - "6739:6739"

  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    restart: always
  
  # tasks:
  #   build: ./web-backend
  #   command: celery -A tasks tasks --loglevel=info
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on:
  #     - redis
  #   restart: always

  celery_worker:
    build: .
    command: celery -A core.tasks.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis
  
  flower:
    build: .
    command: celery flower core.tasks.celery_worker.celery worker --port=5555
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis
      - celery_worker
    restart: always

volumes:
  postgres-data:
